id: crystal.crystal-web
name: Crystal Website
version: 0.1.0
description: the official website for [Crystal](http://crystal.sh)
repository: https://github.com/crystal/crystal-web
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: http://crystal.sh
copyright: 2015 Crystal
modules:
  sh.crystal.coffeescript: v0.1.0
  sh.crystal.express: v0.1.0
  sh.crystal.gitignore: v0.1.0
  sh.crystal.grunt: v0.1.0
  sh.crystal.license: v0.1.0
  sh.crystal.npm: v0.1.0
  sh.crystal.readme: v0.1.0
imports:
  cs-to-js: sh.crystal.coffeescript.JavaScriptTransformer
  express-app: sh.crystal.express.AppGenerator
  express-route: sh.crystal.express.RoutesGenerator
  gitignore: sh.crystal.gitignore.GitignoreGenerator
  grunt: sh.crystal.grunt.GruntfileGenerator
  license: sh.crystal.license.MITGenerator
  npm: sh.crystal.npm.ConfigGenerator
  readme: sh.crystal.readme.ReadmeGenerator
outputs:
  - generator: express-app
    #filename: app.js
    path: src
    #transformer: cs-to-js
    spec:
      body: true
      cookie: true
      port: 8080
      routes: &express-routes
        - title: Crystal
          name: home
          scripts:
            - scripts/page/home.js
          styles:
            - styles/page/home.css
            - styles/page/home/contribute.css
            - styles/page/home/features.css
            - styles/page/home/generators.css
            - styles/page/home/intro.css
            - styles/page/home/usage.css
          uri: /
          view: home
        - name: doc
          title: Crystal Doc
          uri: /doc
          view: doc
        - name: docs
          title: Crystal Docs
          uri: /docs
          view: docs
        - name: help
          title: Crystal Help
          uri: /help
          view: help
        - name: hub
          title: Crystal Hub
          uri: /hub
          view: hub
        #- name: login
        #  title: Crystal Login
        #  uri: /login
        #  view: login
        - name: user
          title: Crystal User
          uri: /user
          view: user
      session:
        secret: PhKbgxBJjBOlAylyzeaBilyXdV0GfoQi
      static:
        font: public/font
        images: public/images
        scripts: public/js
        styles: public/css
      title: Crystal - Open Source Code Generator for Every Language and Platform
      view:
        engine: jade
      views: src/views
  - generator: express-route
    iterator: routes
    path: src/routes
    spec:
      routes: *express-routes
  - generator: gitignore
    spec:
      items:
        - .sass-cache/
        - node_modules/
        - npm-debug.log
  - generator: grunt
    spec:
      loadNpmTasks:
        - grunt-contrib-sass
        - grunt-contrib-watch
      registerTask:
        default:
          - sass
      config:
        pkg: package.json
        sass:
          dist:
            files:
              - expand: true
                cwd: src/sass
                src:
                  - '**/*.scss'
                dest: src/public/css
                ext: .css
            options:
              sourcemap: none
              style: compressed
        watch:
          files:
            - src/public/js/**/*.js
            - src/sass/**/*.scss
            - src/views/**/*.jade
          tasks:
            - sass
            - copy
  - generator: license
    spec:
      copyright: $copyright
  - generator: npm
    spec:
      name: crystal-web
      version: $version
      description: $description
      author: $author
      private: true
      dependencies:
        body-parser: ~1.12.2
        cookie-parser: ~1.3.4
        express: ~4.12.2
        express-session: ~1.10.4
        jade: ~1.9.2
        marked: ~0.3.3
        mkdirp: ~0.5.0
        node-sass: ~2.0.1
        node-sass-middleware: ~0.5.0
        request: ~2.54.0
        sync-request: ~2.0.1
      devDependencies:
        grunt: ~0.4.5
        grunt-contrib-concat: ~0.5.1
        grunt-contrib-copy: ~0.8.0
        grunt-contrib-sass: ~0.9.2
        grunt-contrib-watch: ~0.6.1
      repository:
        type: git
        url: $repository
  - generator: readme
    spec:
      name: $name
      version: $version
      description: $description
scripts:
  build:
    - sudo npm update
  run:
    - sudo grunt
    - sudo coffee src/app.coffee