id: crystal/web
name: Crystal Website
version: 0.1.0
description: official website of [Crystal](http://crystal.sh)
repository: https://github.com/crystal/crystal-web
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: http://crystal.sh
copyright: 2015 Crystal
modules:
  coffeescript.js: v0.1.0
  express.app: v0.1.0
  express.route: v0.1.0
  git.ignore: v0.1.0
  grunt.file: v0.1.0
  license.mit: v0.1.0
  npm.package: v0.1.0
  readme.md: v0.1.0
  redis.config: v0.1.0
  yaml.parse: v0.1.0
imports:
  cs-to-js: coffeescript.js.Transformer
  express-app: express.app.Generator
  express-route: express.route.Generator
  gitignore: git.ignore.Generator
  grunt: grunt.file.Generator
  license: license.mit.Generator
  npm: npm.package.Generator
  readme: readme.md.Generator
  redis: redis.config.Generator
  uri: express.route.URIProcessor
  yaml: yaml.parse.Processor
outputs:
  - generator: express-app
    injector:
      AFTER_MODULES:
        - multer        = require 'multer'
        - bluebird      = require 'bluebird'
        - models        = require './models'
        -
        - '# get db'
        - db = require './db.coffee'
      BEFORE_ROUTES: ./injector/beforeRoutes.coffee
      AFTER_ROUTES: ./injector/appAfterRoutes.coffee
    path: src
    processor: yaml
    spec:
      body: true
      cookie:
        domain: .crystal.sh
      disable:
        - etag
      multer:
        dest: ./uploads/
      port: 8080
      routes: &express-routes
        $processor: yaml
        $value: ./spec/routes
      session:
        secret: PhKbgxBJjBOlAylyzeaBilyXdV0GfoQi
        store:
          host: process.env.CRYSTAL_REDIS_HOST
          port: 6379
          type: redis
      static: &static
        /font: public/font
        /formulas: public/formulas
        /images: public/images
        /scripts: public/js
        /styles: public/css
      title: Crystal - Open Source Code Generator for Every Language and Platform
      view:
        engine: jade
      views: src/views
      
  - generator: express-route
    injector:
      AFTER_MODULES:
        - models = require '../models'
        - 
    iterator: routes
    path: src/routes
    processor:
      - uri
      - yaml
    spec:
      routes:
        $processor:
          - yaml
          - uri
        $value: ./spec/routes
  
  - generator: express-app
    injector:
      AFTER_MODULES:
        - multer        = require 'multer'
        - bluebird      = require 'bluebird'
        - models        = require './models'
        -
        - '# get db'
        - db = require './db.coffee'
      BEFORE_ROUTES: ./injector/beforeRoutes.coffee
      AFTER_ROUTES: ./injector/hubAfterRoutes.coffee
    filename: hub.coffee
    path: src
    spec:
      body: true
      cookie:
        domain: .crystal.sh
      disable:
        - etag
      multer:
        dest: ./uploads/
      port: 8081
      routes: &hub-routes
        hub:
          uri: /
          title: Registry | Crystal
          modules:
            bluebird: bluebird
            formulator: formulator
            marked: marked
            request: request
            yaml: js-yaml
            SearchRegistry: ../formulas/forms/SearchRegistry
          method:
            get:
              local:
                avatar: req.session.avatar
          $injector:
            BEFORE_RENDERING: ./injector/registryBeforeRendering.coffee
      session:
        secret: PhKbgxBJjBOlAylyzeaBilyXdV0GfoQi
        store:
          host: process.env.CRYSTAL_REDIS_HOST
          port: 6379
          type: redis
      static: *static
      title: Crystal - Open Source Code Generator for Every Language and Platform
      view:
        engine: jade
      views: src/views
  
  - generator: express-route
    injector:
      AFTER_MODULES:
        - models = require '../models'
        - 
    iterator: routes
    path: src/routes
    processor:
      - yaml
      - uri
    spec:
      routes: *hub-routes
  
  - generator: gitignore
    spec: gitignore.yml
  - generator: grunt
    spec: grunt.yml
  - generator: license
    spec:
      copyright: $copyright
  - generator: npm
    spec: npm.yml
  - generator: readme
    spec:
      name: $name
      version: $version
      description: $description
  - generator: redis
    path: src/config
    spec:
      daemonize: true
      dbfilename: crystal.rdb
      port: 6379
scripts:
  build:
    - sudo npm update
    - mkdir ~/.crystal/dev/crystal-web/src/models
    - ln -s ~/.crystal/dev/crystal-api/src/models ~/.crystal/dev/crystal-web/src/models
  run:
    #- sudo grunt
    #- redis-server ./src/config/redis.conf
    - coffee src/app.coffee