id: crystal.crystal-web
name: Crystal Website
version: 0.1.0
description: the official website for [Crystal](http://crystal.sh)
repository: https://github.com/crystal/crystal-web
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: http://crystal.sh
copyright: 2015 Crystal
modules:
  sh.crystal.coffeescript: v0.1.0
  sh.crystal.express: v0.1.0
  sh.crystal.gitignore: v0.1.0
  sh.crystal.grunt: v0.1.0
  sh.crystal.license: v0.1.0
  sh.crystal.npm: v0.1.0
  sh.crystal.readme: v0.1.0
imports:
  cs-to-js: sh.crystal.coffeescript.JavaScriptTransformer
  express-gen: sh.crystal.express.AppGenerator
  gitignore-gen: sh.crystal.gitignore.GitignoreGenerator
  grunt-gen: sh.crystal.grunt.GruntfileGenerator
  license-gen: sh.crystal.license.MITGenerator
  npm-gen: sh.crystal.npm.ConfigGenerator
  readme-gen: sh.crystal.readme.ReadmeGenerator
outputs:
  - generator: express-gen
    filename: app.js
    path: lib
    transformer: cs-to-js
    spec:
      body: true
      cookie: true
      port: 80
      routes:
        - uri: /
          url: routes/index.coffee
        - uri: /doc
          src: routes/doc.coffee
        - uri: /docs
          src: routes/docs.coffee
        - uri: /gen
          src: routes/gen.coffee
        - uri: /generators
          src: routes/generators.coffee
        - uri: /help
          src: routes/help.coffee
        - uri: /user
          src: routes/user.coffee
      session:
        secret: PhKbgxBJjBOlAylyzeaBilyXdV0GfoQi
      static:
        font: public/font
        images: public/images
        scripts: public/js
        styles: public/css
      title: Crystal - Open Source Code Generator for Every Language and Platform
      view:
        engine: jade
      views: src/views
  - generator: gitignore-gen
    spec:
      items:
        - .sass-cache/
        - lib/
        - node_modules/
  - generator: grunt-gen
    spec:
      loadNpmTasks:
        - grunt-contrib-copy
        - grunt-contrib-sass
        - grunt-contrib-watch
      registerTask:
        default:
          - sass
          - copy
      config:
        pkg: package.json
        copy:
          main:
            files:
              - expand: true
                cwd: src/code/views/
                src:
                  - '**'
                dest: lib/views/
                filter: isFile
            files:
              - expand: true
                cwd: src/code/public/js/
                src:
                  - '**'
                dest: lib/public/js/
                filter: isFile
        sass:
          dist:
            files:
              - expand: true
                cwd: src/code/sass
                src:
                  - '**/*.scss'
                dest: lib/public/css
                ext: .css
            options:
              sourcemap: none
              style: compressed
        watch:
          files:
            - src/code/public/js/**/*.js
            - src/code/sass/**/*.scss
            - src/code/views/**/*.jade
          tasks:
            - sass
            - copy
  - generator: license-gen
    spec:
      copyright: $copyright
  - generator: npm-gen
    spec:
      name: crystal-web
      version: $version
      description: $description
      author: $author
      private: true
      dependencies:
        body-parser: ~1.12.2
        cookie-parser: ~1.3.4
        express: ~4.12.2
        express-session: ~1.10.4
        jade: ~1.9.2
        marked: ~0.3.3
        mkdirp: ~0.5.0
        node-sass: ~2.0.1
        node-sass-middleware: ~0.5.0
        request: ~2.54.0
        sync-request: ~2.0.1
      devDependencies:
        grunt: ~0.4.5
        grunt-contrib-concat: ~0.5.1
        grunt-contrib-copy: ~0.8.0
        grunt-contrib-sass: ~0.9.2
        grunt-contrib-watch: ~0.6.1
      repository:
        type: git
        url: $repository
  - generator: readme-gen
    spec:
      name: $name
      version: $version
      description: $description
scripts:
  build:
    - sudo npm install
    - sudo npm update
  run:
    - sudo coffee lib/app.coffee