id: crystal.web
name: Crystal Website
version: 0.1.0
description: the official website for [Crystal](http://crystal.sh)
repository: https://github.com/crystal/crystal-web
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: http://crystal.sh
copyright: 2015 Crystal
modules:
  official.coffeescript: v0.1.0
  official.dynamodb: v0.1.0
  official.express: v0.1.0
  official.gitignore: v0.1.0
  official.grunt: v0.1.0
  official.license: v0.1.0
  official.npm: v0.1.0
  official.readme: v0.1.0
imports:
  cs-to-js: official.coffeescript.JavaScriptTransformer
  dynamodb: official.dynamodb.ModelGenerator
  express-app: official.express.AppGenerator
  express-route: official.express.RouteGenerator
  gitignore: official.gitignore.GitignoreGenerator
  grunt: official.grunt.GruntfileGenerator
  license: official.license.MITGenerator
  npm: official.npm.ConfigGenerator
  readme: official.readme.ReadmeGenerator
outputs:
  - generator: express-app
    #filename: app.js
    path: src
    #transformer: cs-to-js
    spec:
      body: true
      cookie: true
      port: 8080
      routes: &express-routes
        # GET /
        - method: GET
          title: Crystal
          name: home
          scripts:
            - scripts/page/home.js
          styles:
            - styles/page/home.css
            - styles/page/home/contribute.css
            - styles/page/home/features.css
            - styles/page/home/generators.css
            - styles/page/home/intro.css
            - styles/page/home/usage.css
          uri: /
          view: home
          
        # GET /doc
        - method: GET
          name: doc
          title: Crystal Doc
          uri: /doc
          view: doc
          
        # GET /docs
        - method: GET
          name: docs
          title: Crystal Docs
          uri: /docs
          view: docs
        
        # GET /help
        - method: GET
          name: help
          title: Crystal Help
          uri: /help
          view: help
        
        # GET /hub
        - method: GET
          name: hub
          title: Crystal Hub
          uri: /hub
          view: hub
        
        # GET /login
        - method: GET
          name: login
          title: Crystal Login
          uri: /login
          view: login
        
        # GET /login/github
        - method: GET
          name: github
          title: Crystal Login
          uri: /login/github
          view: github
        
        # GET /logout
        - method: GET
          name: logout
          redirect: /
          title: Crystal Logout
          uri: /logout
        
        # GET /module
        - method: GET
          name: module
          title: Crystal Module
          uri: /module/:name
        
        # GET /user
        - method: GET
          name: user
          title: Crystal User
          uri: /user
          view: user
          
      session:
        secret: PhKbgxBJjBOlAylyzeaBilyXdV0GfoQi
        store:
          host: redis.crystal.sh
          port: 6379
          type: redis
      static:
        /font: public/font
        /images: public/images
        /scripts: public/js
        /styles: public/css
      title: Crystal - Open Source Code Generator for Every Language and Platform
      view:
        engine: jade
      views: src/views
      
  - generator: express-route
    iterator: routes
    path: src/routes
    spec:
      routes: *express-routes
  - generator: gitignore
    spec:
      items:
        - .sass-cache/
        - node_modules/
        - npm-debug.log
  - generator: grunt
    spec:
      loadNpmTasks:
        - grunt-contrib-sass
        - grunt-contrib-watch
      registerTask:
        default:
          - sass
      config:
        pkg: package.json
        sass:
          dist:
            files:
              - expand: true
                cwd: src/sass
                src:
                  - '**/*.scss'
                dest: src/public/css
                ext: .css
            options:
              sourcemap: none
              style: compressed
        watch:
          files:
            - src/public/js/**/*.js
            - src/sass/**/*.scss
            - src/views/**/*.jade
          tasks:
            - sass
            - copy
  - generator: license
    spec:
      copyright: $copyright
  - generator: npm
    spec:
      name: crystal-web
      version: $version
      description: $description
      author: $author
      private: true
      dependencies:
        aws-sdk: ~2.1.33
        bluebird: ~2.9.27
        body-parser: ~1.12.2
        connect-redis: ~2.3.0
        cookie-parser: ~1.3.4
        express: ~4.12.2
        express-session: ~1.10.4
        forms: ~1.1.1
        jade: ~1.9.2
        marked: ~0.3.3
        mkdirp: ~0.5.0
        node-sass: ~2.0.1
        node-sass-middleware: ~0.5.0
        node-uuid: ~1.4.3
        query-string: ~2.3.0
        redis: ~0.12.1
        request: ~2.54.0
      devDependencies:
        grunt: ~0.4.5
        grunt-contrib-concat: ~0.5.1
        grunt-contrib-copy: ~0.8.0
        grunt-contrib-sass: ~0.9.2
        grunt-contrib-watch: ~0.6.1
      repository:
        type: git
        url: $repository
  - generator: readme
    spec:
      name: $name
      version: $version
      description: $description
scripts:
  build:
    - sudo npm update
  run:
    - sudo grunt
    - sudo coffee src/app.coffee